### ISSUE TITLE
Firefox indicates that the connection isn't secure

### ISSUE THREAD

**Issue by ghost** [rmellema/tutoring#12]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
The little thingy in the top left hand corner that shows if a website is secure or not is indicating that CACTuS isn't secure while browsing in Firefox

* **If the current behavior is a bug, please provide the steps to reproduce**
browse via firefox

* **What is the expected behavior?**
that the website is secure in firefox

* **What is the motivation / use case for changing the behavior?**
everything should be secure

* **Please tell us about your environment:**

  - Browser: [Firefox XX ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
Reported by Joost and copied from the studee trello board of issues

**Comment by rmellema** [comment]
This has been solved by Martijn.
