### ISSUE TITLE
There's no 404 error page

### ISSUE THREAD

**Issue by ghost** [rmellema/tutoring#13]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
please this one is self explanatory, make a 404 page

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome
    XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX
WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)

**Comment by NicoStegeman** [comment]
Added error pages for codes 400, 403, 404 and 500 with instruction on how to contact the committee.
