### ISSUE TITLE
When the password is changed on svcover.nl, the user remains logged in on CACTuS

### ISSUE THREAD

**Issue by ghost** [rmellema/tutoring#8]
**Note: for support questions, please mail tutoring.svcover.nl**. This repository's
issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
    at the top of this template.

* **What is the current behavior?**
When the user's password is changed on svcover.nl, the user remains logged in on CACTuS (it should instead ask you to enter your password again)

* **If the current behavior is a bug, please provide the steps to reproduce**
> Log into CACTuS
> close tab
> go to svcover.nl
> change password
 > go back to cactus and you will be logged in

* **What is the expected behavior?**
For the final stage CACTuS will send you back to the login page

* **What is the motivation / use case for changing the behavior?**
Probably security related

* **Please tell us about your environment:**

  - Browser: [all | Chrome XX  ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
  suggestions how to fix, links for us to have context, eg. stackoverflow,
gitter, etc)
This was listed on StudCee's trello page of issues

**Comment by rmellema** [comment]
Closed by #24
